import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >


      <body className="min-h-full flex flex-col">
         <header className="px-4 py-3 bg-green-950 justify-between items-center border-2 flex gap-5">
          <img className="w-[60px]" src="/logo.jpg" alt="" />

         <div className="flex gap-5">
            <button className="bg-amber-400 text-white px-4 py-2 rounded-md hover:bg-blue-700 cursor-pointer duration-200">
              Cars
            </button>
            <button className="bg-amber-400 text-white px-4 py-2 rounded-md hover:bg-blue-700 cursor-pointer duration-200">
              Review
            </button>

         </div>
         </header>
        
        {children}
   

      </body>
    </html>
  );
}
